# Generated by Django 5.2.17 on 2026-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['unit', 'date'], name='payments_pa_unit_id_16a729_idx'),
        ),
    ]
