# Generated by Django 6.1.1 on 2026-09-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partial', 'پرداخت جزئی'), ('paid', 'پرداخت شده'), ('cancelled', 'ابطال شده')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='buildings.building')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='buildings.unit')),
            ],
            options={
                'ordering': ['-year', '-month', 'unit__number'],
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='charges.charge')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fixed', 'مبلغ ثابت هر واحد'), ('area', 'به ازای هر متر مربع'), ('per_resident', 'به ازای هر نفر'), ('parking', 'به ازای هر پارکینگ'), ('storage', 'به ازای هر انبار'), ('extra', 'مبلغ اضافه ثابت'), ('discount', 'تخفیف (کسور)')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rules', to='buildings.building')),
            ],
            options={
                'ordering': ['building', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['building', 'year', 'month'], name='charges_cha_buildin_9e49d8_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['unit', 'status'], name='charges_cha_unit_id_6371b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('unit', 'year', 'month'), name='unique_billing_period_per_unit'),
        ),
    ]
