# Generated by Django 6.1.1 on 2026-09-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('kind', models.CharField(choices=[('charge', 'شارژ'), ('payment', 'پرداخت'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='بستانکار')),
                ('description', models.CharField(max_length=300, verbose_name='شرح')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='buildings.building')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['building', 'date'], name='ledger_ledg_buildin_39ece8_idx'), models.Index(fields=['kind'], name='ledger_ledg_kind_8f7fb7_idx')],
            },
        ),
    ]
