# Generated by Django 6.1.1 on 2026-09-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'آب'), ('electricity', 'برق'), ('gas', 'گاز'), ('cleaning', 'نظافت'), ('elevator', 'آسانسور'), ('repairs', 'تعمیرات'), ('other', 'سایر')], default='other', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buildings.building')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['building', 'date'], name='expenses_ex_buildin_ad869a_idx')],
            },
        ),
    ]
