# Generated by Django 5.2.17 on 2026-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='پیوست'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('transfer', 'انتقال بانکی')], default='cash', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره پیگیری'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=150, verbose_name='پرداخت\u200cکننده / فروشنده'),
        ),
    ]
