# Generated by Django 6.1.1 on 2026-09-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'انجام\u200cشده'), ('rejected', 'رد\u200cشده')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='buildings.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='maintenance_status_0773c2_idx')],
            },
        ),
    ]
