# Generated by Django 6.1.1 on 2026-09-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('parking_count', models.PositiveSmallIntegerField(default=0)),
                ('storage_count', models.PositiveSmallIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building')),
            ],
            options={
                'ordering': ['building', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('tenant', 'مستأجر')], default='owner', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('moved_in', models.DateField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='buildings.unit')),
            ],
            options={
                'ordering': ['unit', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building'], name='buildings_u_buildin_a6ac3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_unit_number_per_building'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['unit', 'is_active'], name='buildings_r_unit_id_c63fb7_idx'),
        ),
    ]
